version: '3.8'

services:
  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: student-management-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Praveen@16
      MYSQL_DATABASE: student_management
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Node.js Application Service
  app:
    build: .
    container_name: student-management-app
    restart: always
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: Praveen@16
      DB_NAME: student_management
      PORT: 7373
    ports:
      - "7373:7373"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
